<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Webpatser\\Uuid' => array($vendorDir . '/webpatser/laravel-uuid/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
);
